name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  wait-for-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Tests to Complete
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    needs: wait-for-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Test Results
        run: |
          if [[ "${{ job.status }}" == 'failure' ]]; then
            gh pr comment ${{ github.event.pull_request.number }} --body "Tests Failed. Closing PR."
            gh pr close ${{ github.event.pull_request.number }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-Merge Dependabot PRs
        if: success() && github.actor == 'dependabot[bot]'
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
