# .github/workflows/tests.yml
name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.session }} ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.11", os: "ubuntu-latest", session: "pre-commit" }
          - { python: "3.11", os: "ubuntu-latest", session: "safety" }
          #- { python: "3.12", os: "ubuntu-latest", session: "mypy" }
          #- { python: "3.11", os: "ubuntu-latest", session: "mypy" }
          #- { python: "3.10", os: "ubuntu-latest", session: "mypy" }
          #- { python: "3.9", os: "ubuntu-latest", session: "mypy" }
          #- { python: "3.8", os: "ubuntu-latest", session: "mypy" }
          #- { python: "3.12", os: "ubuntu-latest", session: "tests" }
          - { python: "3.11", os: "ubuntu-latest", session: "tests" }
          - { python: "3.10", os: "ubuntu-latest", session: "tests" }
          - { python: "3.9", os: "ubuntu-latest", session: "tests" }
          - { python: "3.8", os: "ubuntu-latest", session: "tests" }
          - { python: "3.11", os: "windows-latest", session: "tests" }
          - { python: "3.11", os: "macos-latest", session: "tests" }
          - { python: "3.11", os: "ubuntu-latest", session: "xdoctest" }
          - { python: "3.11", os: "ubuntu-latest", session: "docs-build" }

    env:
      NOXSESSION: ${{ matrix.session }}
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade Pip
        run: |
          pip install --constraint="${{ github.workspace }}/.github/workflows/constraints.txt" pip
          pip --version

      - name: Upgrade Pip in Virtual Environments
        shell: python
        run: |
          import os
          import pip

          with open(os.environ["GITHUB_ENV"], mode="a") as io:
              print(f"VIRTUALENV_PIP={pip.__version__}", file=io)

      - name: Install Poetry
        run: |
          pipx install --pip-args=--constraint="${{ github.workspace }}/.github/workflows/constraints.txt" poetry
          poetry --version

      - name: Install Nox
        run: |
          pipx install --pip-args=--constraint="${{ github.workspace }}/.github/workflows/constraints.txt" nox
          nox --version

      - name: Install Nox Poetry
        run: |
          pip install .

      - name: Compute pre-commit cache key
        if: matrix.session == 'pre-commit'
        id: pre-commit-cache
        shell: python
        run: |
          import hashlib
          import sys

          python = "py{}.{}".format(*sys.version_info[:2])
          payload = sys.version.encode() + sys.executable.encode()
          digest = hashlib.sha256(payload).hexdigest()
          result = "${{ runner.os }}-{}-{}-pre-commit".format(python, digest[:8])

          print("::set-output name=result::{}".format(result))

      - name: Restore pre-commit cache
        uses: actions/cache@v4
        if: matrix.session == 'pre-commit'
        with:
          path: ~/.cache/pre-commit
          key: ${{ steps.pre-commit-cache.outputs.result }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ steps.pre-commit-cache.outputs.result }}-

      - name: Run Nox
        run: |
          nox --python=${{ matrix.python }}

      - name: Upload coverage data
        if: always() && matrix.session == 'tests'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ runner.os }}-${{ matrix.python }}
          path: .coverage.*
          include-hidden-files: true

      - name: Upload Documentation
        if: matrix.session == 'docs-build'
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade Pip
        run: |
          pip install --constraint="${{ github.workspace }}/.github/workflows/constraints.txt" pip
          pip --version

      - name: Install Poetry
        run: |
          pipx install --pip-args=--constraint="${{ github.workspace }}/.github/workflows/constraints.txt" poetry
          poetry --version

      - name: Install Nox
        run: |
          pipx install --pip-args=--constraint="${{ github.workspace }}/.github/workflows/constraints.txt" nox
          nox --version

      - name: Install Nox Poetry
        run: |
          pip install .

      - name: Download coverage data
        uses: actions/download-artifact@v4
        with:
          # Use pattern since articaft name is dynamic
          pattern: coverage-data-*
          path: .coverage.*
          merge-multiple: true

      # With the new changes with upload-artifact, the .coverage.* files are now
      # uploaded as a zip by their running os and Python version. Since the
      # download-artifact action extracts them, they are now in a folder with the
      # same name as the zip file. We need to move them to the root directory
      # for Nox to be able to find them.
      - name: Extract coverage data
        run: |
          ls -la ${{ github.workspace }}/.coverage.*
          mv -v ${{ github.workspace }}/.coverage.*/.coverage.* ${{ github.workspace }}/
          rm -vrf ${{ github.workspace }}/.coverage.*/

      - name: Combine Coverage Data and Display Human Readable Report
        run: |
          nox --session=coverage

      - name: Create Coverage Report
        run: |
          nox --session=coverage -- xml

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: xransum/valkyrie-tools
